// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArXE3A54nGDdSTyTpY4YxwErC8s4CMiKI',
    appId: '1:219180575444:web:0d68b0eb91aa7670a22941',
    messagingSenderId: '219180575444',
    projectId: 'ali-projects-d86ba',
    authDomain: 'ali-projects-d86ba.firebaseapp.com',
    storageBucket: 'ali-projects-d86ba.appspot.com',
    measurementId: 'G-08LRTZM0JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVyqVaZg6aFtHlvhFXEkyaPJZQIFR_qw',
    appId: '1:219180575444:android:344ff9b3f2dc4f48a22941',
    messagingSenderId: '219180575444',
    projectId: 'ali-projects-d86ba',
    storageBucket: 'ali-projects-d86ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVB3PuvF6w3Tw2g55pnvv2PwKIBJewpzw',
    appId: '1:219180575444:ios:e0d587ed1a6e77bea22941',
    messagingSenderId: '219180575444',
    projectId: 'ali-projects-d86ba',
    storageBucket: 'ali-projects-d86ba.appspot.com',
    iosBundleId: 'com.diyBoba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVB3PuvF6w3Tw2g55pnvv2PwKIBJewpzw',
    appId: '1:219180575444:ios:5f8ff0c5e1abb562a22941',
    messagingSenderId: '219180575444',
    projectId: 'ali-projects-d86ba',
    storageBucket: 'ali-projects-d86ba.appspot.com',
    iosBundleId: 'com.diyBoba.RunnerTests',
  );
}
